### ISSUE TITLE
"No new emails" alert is unnecessary

### ISSUE THREAD

**Issue by simonbcn** [shumingch/GmailMessageTray#1]
The "_No new emails_" alert is unnecessary and it's annoying. 
Perhaps an option to disable this behavior would be ok.

**Comment by shumingch** [comment]
Does it popup for you or just sit in the message tray?

**Comment by simonbcn** [comment]
No popup, only alert in message tray.

**Comment by shumingch** [comment]
https://github.com/shumingch/GmailMessageTray/commit/ffc31adf8db364b586b206be560e644307997fe2
