### ISSUE TITLE
Error 403 when opening clicking on notification

### ISSUE THREAD

**Issue by Goostavo** [shumingch/GmailMessageTray#10]
I am using Ubuntu Gnome 17.04.  With firefox as the default browser (distro default browser).

The extension works as expected, receiving all notifications on top panel, but when I click on an received e-mail notification, it tries to open in browser but I get a page with the error:

`
Forbidden

Error 403
`

The generated link when i clicked was:
`https://mail.google.com/mail/u/0?account_id=myEmail@gmail.com&message_id=0123456789ABCDEF&view=conv&extsrc=atom`

**Comment by shumingch** [comment]
Could you verify that "Mail" is checked in your Google Account in the Gnome Online Accounts Settings? 
![image](https://user-images.githubusercontent.com/15637542/28097837-96023ad0-6680-11e7-8633-cf9f34daa2e7.png)

**Comment by Goostavo** [comment]
Hey @shumingch 

I am logged in. I've made a few tests and found out whats happening!

I'm using two google accounts. On is my personal, and the second one my professional one. The messages that i tested and was getting FORBIDDEN was on my second account (the professional).
The link has an `/mail/u/0` if i change it to `/mail/u/1`it refers the right account and there is no FORBIDDEN error.

I've made a fast research on google, and this guy had exactly the same problem in another application. On this link they show how to refer the right account without using this numeric reference.
https://productforums.google.com/forum/#!topic/gmail/2hEi6wcgW8M

**Comment by shumingch** [comment]
Thanks for figuring out the problem! From just glancing at it, the solution
you gave me doesn't seem to link to a specific email, it just goes to the
inbox. So I'm going to have to figure something else out.

**Comment by shumingch** [comment]
Ok, after trying it out, it actually worked as you said. If you want you can do a pull request, but i'm working on adding Outlook support now.

**Comment by shumingch** [comment]
Reopening issue. I tried to use https://accounts.google.com/AccountChooser/signinchooser? instead of https://accounts.google.com/AccountChooser? so that the user doesn't have to choose the account every time, but that didn't work.
