### ISSUE TITLE
Error Scanning inbox: code 2

### ISSUE THREAD

**Issue by d3sign3r** [shumingch/GmailMessageTray#11]
I m using Gnome 3.24 and Fedora 26. I am getting the error message above inside my notifications box at the panel. Any solution??

**Comment by shumingch** [comment]
It usually means you aren't connected to the internet. Can you check and
see if you still get notifications for new emails?

**Comment by shumingch** [comment]
Oh, also try restarting your computer. There is a bug in gnome that breaks
online accounts if you ever log out of your Linux account.

**Comment by d3sign3r** [comment]
i tried everything as you mentioned but still the same. Never mind its a nice extension and i will keep it even with this little bug.

**Comment by shumingch** [comment]
Thank you. If you ever find any more information about your error please
let me know.

**Comment by shumingch** [comment]
Maybe this will help: I found out that error 2 is associated with the error 'Error resolving “mail.google.com”: Name or service not known'

Or, if you have a microsoft account, it would be: 'Error resolving “mail.google.com”: Name or service not known'

This could indicate that your system-wide dns settings are wrong.
