### ISSUE TITLE
GDbus error org.gnome.Online.Accounts.OAuth2Based

### ISSUE THREAD

**Issue by augias** [shumingch/GmailMessageTray#2]
Evening! I am getting the following notification despite being correctly synched to my google accounts on gnome.

> gdbus.error.org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.gnome.Online.Accounts.OAuth2Based
on object at path /org/gnome/OnlineAccounts/Accounts/account

> 
Using Ubuntu-Gnome 17.04, all packages stock and up to date. Any info i can reasonably provide I would be happy to share.

![screenshot from 2017-05-27 23-05-29](https://cloud.githubusercontent.com/assets/19480035/26525809/09259926-4331-11e7-98a3-28a6f34ba6d3.png)
'

**Comment by augias** [comment]
I believe I must have reported the same issue explained in the main page here re. authentication error, and failed to recognize the same. Closed

**Comment by shumingch** [comment]
So you rebooted and it was fixed?

**Comment by augias** [comment]
Yes, i rebooted and it stopped displaying the error notifications. Thanks
for checking in with me to confirm :)

On May 28, 2017 08:16, "Shuming Chan" <notifications@github.com> wrote:

So you rebooted and it was fixed?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/shumingch/GmailMessageTray/issues/2#issuecomment-304510094>,
or mute the thread
