### ISSUE TITLE
Extension spams with error notifications on connectivity loss

### ISSUE THREAD

**Issue by SolarLiner** [shumingch/GmailMessageTray#4]
OS: Ubuntu 17.04, GNOME 3.24

When disconnected, the extensions continues to check for emails and pops up an error every check cycle.
I think it'd be better for the extension to be aware of the connectivity state of the machine and pause checking when the computer is offline.

**Comment by shumingch** [comment]
Would you prefer a single error that doesn't popup, but still stays in the message tray?

**Comment by SolarLiner** [comment]
That would be preferable. Maybe the notification should pop-up to signal loss of connectivity anyway, but not every time the notification checks for email.

**Comment by rusins** [comment]
I too am annoyed by the constant notifications telling me my laptop is offline, perhaps connectivity loss and other issues could just be written to a log file, or better yet, the extension could detect when the computer really is offline, and then disable the error notifications.

**Comment by shumingch** [comment]
This should be fixed in version 5. You're going to have to wait until the gnome shell devs accept this version. Here is the current status: https://extensions.gnome.org/review/6968

**Comment by shumingch** [comment]
@rusins try installing the new version and let me know what you think.

**Comment by rusins** [comment]
Getting occasional Error code 7 and Error code 2 pop-up notifications with Version 6 of the extension, seems to be happening immediately after waking laptop up from sleep / right when connecting to the internet. (No idea what those error codes mean)

When completely offline, the extension gives the 'Failed to read inbox' error, but it doesn't pop up as a notification, which is good! :) (Exactly how I'd like it – hidden in the message tray.)

Of course the extension still works perfectly in other cases. :D

**Comment by shumingch** [comment]
Does error code 7 and 2 go away after a couple minutes?

**Comment by rusins** [comment]
Sorry for not responding sooner, was hoping I'd notice those errors again, but I haven't. Either they stopped appearing for me, or they do go away after a couple of minutes and I just haven't noticed them since. My only grudge is that both the "no new messages" and 'error when offline' messages stack up after a while and fill the message tray, however I noticed you include an option for disabling one of those notifications completely, so all should be good.
Thank you once again! This is very valuable work you have done! :D

**Comment by rusins** [comment]
Nvm, the errors back, and they stack up and fill the message tray pretty quickly. So do the "no new mail" messages. It is quite annoying.
