### ISSUE TITLE
Limit notifications to new ones since last update

### ISSUE THREAD

**Issue by HolgerSontag** [shumingch/GmailMessageTray#7]
Hi,

I really like the idea, as it mixes extremely well with nativefier to finally create a usable mail client for Linux. The only thing that is bothering me is, that I have some 2000 or so really old unread messages, that I do not need to see. I think it would make more sense to limit the notifications to new ones only, and, if that is not possible, show only notifications not older than one hour or so.

cheers,
Holger

**Comment by shumingch** [comment]
How about an option for max number of notifications at startup?

**Comment by HolgerSontag** [comment]
even better!
