### ISSUE TITLE
Option for chosing between inbox and gmail or even an application

### ISSUE THREAD

**Issue by HolgerSontag** [shumingch/GmailMessageTray#8]
Hi again,

since this project seems to be very active, there is another idea I would like to add to the list of suggestions:
How about an option about what should be opened when the notification is clicked?
Currently you have ` Util.trySpawnCommandLine("xdg-open " + link);`
Which opens the default browser (Chrome for me) and Gmail. This is working well and I can see where this is coming from, as this is the **Gmail** message tray ;).

Now, I am currently using google inbox (because it is simply awesome) alongside nativefier to have it as a plain "Zenware"-like desktop app. I understand that calling the respective link insie some electron box is probably a project you do not want to touch. But for me it would already be enough if this message would simply open the executable, or call it into focus if its already open. Basically there could be an option to switch `xgd-open` to something else, such as `inbox.desktop`. And for those, that prefer inbox, you might want to add the option to not call gmail, but inbox instead.

/edit: I just saw, that you can actually use the default mail client. That should work for me.

cheers,
Holger

**Comment by shumingch** [comment]
Can you get it to work with xdg-email?

**Comment by HolgerSontag** [comment]
sort of... problem is, that its not checking if the application is already running. Something like this would probably work better: `sh -c "if test $(wmctrl -vxa inbox 2>&1 | wc -l) -eq 1; then /path/to/inbox; fi"` I have hardcoded it and it works nicely for me. You could add an option with a custom field and application name that basically fills in the blanks and set wmctrl as an optional dependency.
