### ISSUE TITLE
Enable proxy connection

### ISSUE THREAD

**Issue by felansu** [shumingch/GmailMessageTray#9]

**Comment by shumingch** [comment]
Are you able to use a system-wide proxy? For example, in Ubuntu you can do the following: https://help.ubuntu.com/stable/ubuntu-help/net-proxy.html

**Comment by felansu** [comment]
@shumingch Yes, i'm using system-wide proxy.

**Comment by shumingch** [comment]
It seems to be working for me. Are you getting an error on your system? Which distribution are you using?

**Comment by felansu** [comment]
I'm using ubuntu gnome 16.04 LTS ! No error
